---
dotfiles:
- name: default_i3
  filepath: test/i3/config
  hosts:
    - hostname: desktop
      path: /home/user/.config/test/i3/config
      frozen: false

    - hostname: blade
      path: /home/user/.config/i3/i3
      frozen: false

- name: polybar/
  filepath: test/polybar/
  hosts:
    - hostname: desktop
      path: /home/user/.config/test/polybar/
      frozen: false
    - hostname: blade
      path: /home/user/.config/polybar/
      frozen: false

- name: .vimrc
  filepath: test/vim/.vimrc
  hosts:
    - hostname: desktop
      path: /home/user/.config/test/vim/.vimrc
      frozen: false
    
    - hostname: blade
      path: /home/user/.vimrc
      frozen: false

  
